version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: stream-radar-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: radar
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: stream_radar
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
